package pt.unparallel.fiesta.tester.resources;

import java.util.LinkedList;
import java.util.Arrays;

public class QuantityKind {
	
	private static LinkedList<String> kinds = new LinkedList<String>(Arrays.asList(
		
			"Acceleration",
			"Acceleration Instantaneous",
			"AirPollution",
			"AirQuality",
			"AlcoholLevel",
			"Angular",
			"BatteryLevel",
			"BloodGlucose",
			"Calcium",
			"Capacitance",
			"ChemicalAgentAtmosphericConcentration",
			"Chemical Agent Atmospheric Concentration Air Particles",
			"Chemical Agent Atmospheric Concentration CO",
			"Chemical Agent Atmospheric Concentration NO2",
			"Chemical Agent Atmospheric Concentration O3",
			"Cholesterol",
			"CloudCover",
			"CO2",
			"Communication",
			"Conductivity",
			"DewPoint",
			"Delta Dew Point",
			"Dew Point Temperature",
			"Direction",
			"Direction Azimuth",
			"Direction Heading",
			"Distance",
			"ElectricCharge",
			"ElectricCurrent",
			"ElectricField",
			"Electric Field 1800 MHz",
			"Electric Field 2100 MHz",
			"Electric Field 2400 MHz",
			"Electric Field 900 MHz",
			"ElectricPotential",
			"ElectricalResistance",
			"Energy",
			"FillLevel",
			"Fill Level Gas Tank",
			"Fill Level Gas Tank 1",
			"Fill Level Gas Tank 2",
			"Fill Level Waste Container",
			"Frequency",
			"FuelConsumption",
			"Fuel Consumption Instantaneous",
			"Fuel Consumption Total",
			"HeartBeat",
			"Humidity",
			"Illuminance",
			"Weather Luminosity",
			"LeafWetness",
			"Location",
			"LuminousFlux",
			"LuminousIntensity",
			"MagneticField",
			"MagneticFluxDensity",
			"Mass",
			"Mileage",
			"Mileage Distance To Service",
			"Mileage Total",
			"Motion",
			"MotionState",
			"Motion State Vehicle",
			"NumberStep",
			"PH",
			"Position",
			"Position Altitude",
			"Position Latitude",
			"Position Longitude",
			"Potassium",
			"Power",
			"ActivePower",
			"Reactive Power",
			"Precipitation",
			"Weather Precipitation",
			"Presence",
			"PresenceState",
			"Presence State Driver Card",
			"Presence State Driver Card 1",
			"Presence State Driver Card 2",
			"Presence State Emergency Vehicle",
			"Presence State Parking",
			"Presence State People",
			"Pressure",
			"Atmospheric Pressure",
			"Blood pressure",
			"Diastolic Blood pressure",
			"Systolic Blood pressure",
			"Proximity",
			"Rainfall",
			"RecognizedActivity",
			"RelativeHumidity",
			"RFIDQuantityKind",
			"RFID Measurement Type",
			"Animal",
			"Book",
			"CD",
			"Clothes",
			"DVD",
			"Food",
			"Luggage",
			"ParkingSpace",
			"Passport",
			"Payment Card",
			"Toll",
			"TransitPass",
			"RoadOccupancy",
			"RotationalSpeed",
			"Rotational Speed",
			"Rotational Speed Engine",
			"Salinity",
			"SkinConductance",
			"Sodium",
			"SoilHumidity",
			"SoilMoistureTension",
			"SolarRadiation",
			"SoundPressureLevel",
			"Sound Pressure Level",
			"Sound Pressure Level Ambient",
			"Sound",
			"Speed",
			"Speed Average",
			"Speed Instantaneous",
			"Speed Median",
			"SPO2",
			"SunPositionDirection",
			"SunPositionElevation",
			"Temperature",
			"Air Temperature, Weather Temperature, Ambient Temperature",
			"Board Temperature",
			"Body Temperature",
			"Building/Room Temperature",
			"Room Temperature",
			"Food Temperature",
			"Household Appliance Temperature",
			"Road Temperature",
			"Soil Temperature",
			"Temperature Engine",
			"Waste Container",
			"Water Temperature",
			"TimeRelatedState",
			"Time Related State",
			"Time Related State Driver",
			"Time Related State Driver 1",
			"Time Related State Driver 2",
			"Timestamp",
			"TrafficCongestion",
			"TrafficIntensity",
			"VehicleOverspeedState",
			"Visibility",
			"WaterLevel",
			"Weight",
			"WindChill",
			"WindDirection",
			"WindSpeed",
			"WorkingState",
			"Working State",
			"Working State Driver",
			"Working State Driver 1",
			"Working State Driver 2",
			"Others"
	));
	
	private static LinkedList<String> kindsToTest = new LinkedList<String>(Arrays.asList(
			"Temperature","Sound","Speed","Pressure","Humidity"
	));
	
	public static boolean validQuantityKind(String quantityKind) {
		
			return kinds.contains(quantityKind);
	}
	
	public static String quantityKindFromReducedList(int index) {
		return kindsToTest.get(index);
	}
}
